import { strict as assert } from "node:assert";
import { GovernanceController } from "../core/governance/controller";
import { InMemoryApprovalStore } from "../core/governance/store";
import { AgentTask } from "../core/agent-runtime/types";
const store=new InMemoryApprovalStore(); const governance=new GovernanceController(store);
const task:AgentTask={task_id:"t1",company_id:"c1",objective:"Publish production changes",assigned_agent:"builder",priority:"high",inputs:{},constraints:[],dependencies:[],expected_outcome:"Production deployment",approval:{required:false,status:"not_required"},status:"queued"};
const decision=await governance.authorize(task,"builder","EXECUTE","high");
assert.equal(decision.allowed,false); assert.equal(decision.approvalRequired,true); assert.ok(decision.approvalId);
const pending=await store.get(decision.approvalId!); assert.equal(pending?.status,"pending");
const approved=await store.decide({approval_id:decision.approvalId!,status:"approved",decided_by:"human"}); assert.equal(approved.status,"approved");
console.log("Governance tests passed.");