import { randomUUID } from "node:crypto";
import { AgentDefinition } from "../agent-runtime/types";
import { LLMRouter } from "../llm/types";
import { MemoryStore } from "../memory/types";
import { RuntimeStore } from "../persistence/runtime-store";
import { buildPlanningPrompt } from "./prompts";
import { CompanyGoal, OrchestrationPlan, OrchestratorAgentCatalog, PlannedTask } from "./types";
import { validatePlan } from "./validator";
export class AICEOPlanner {
  constructor(private readonly router: LLMRouter, private readonly agents: AgentDefinition[], private readonly runtimeStore?: RuntimeStore, private readonly memoryStore?: MemoryStore) {}
  async plan(goal: CompanyGoal): Promise<OrchestrationPlan> {
    const memories = this.memoryStore ? await this.memoryStore.search({ company_id: goal.company_id, query: goal.objective, limit: 12 }) : [];
    const catalog: OrchestratorAgentCatalog[] = this.agents.map(a => ({ id: a.id, purpose: a.purpose }));
    const enrichedGoal = { ...goal, context: { ...(goal.context ?? {}), relevant_memory: memories.map(m => ({ type: m.memory_type, key: m.memory_key, content: m.content, confidence: m.confidence })) } };
    const response = await this.router.generate({ taskType: "structured", responseFormat: "json", temperature: 0.1, messages: [{ role: "system", content: "You are the planning layer of an autonomous company operating system. Produce safe, executable plans; never claim work was executed." }, { role: "user", content: buildPlanningPrompt(enrichedGoal, catalog) }], metadata: { company_id: goal.company_id, component: "ai-ceo-planner" } });
    const parsed = parsePlan(response.text);
    const tasks: PlannedTask[] = parsed.tasks.map((task: PlannedTask, index: number) => ({ ...task, task_id: task.task_id || `task-${index + 1}` }));
    const plan: OrchestrationPlan = { plan_id: randomUUID(), company_id: goal.company_id, objective: goal.objective, rationale: parsed.rationale ?? "", tasks, risks: parsed.risks ?? [], approvals_needed: parsed.approvals_needed ?? [], evidence: [`Planning response generated by ${response.provider}/${response.model}`] };
    validatePlan(plan, this.agents);
    if (this.runtimeStore) for (const task of plan.tasks) await this.runtimeStore.saveTask({ task_id: task.task_id, company_id: goal.company_id, parent_task_id: task.parent_task_id ?? null, objective: task.objective, assigned_agent: task.assigned_agent, priority: task.priority, inputs: task.inputs, constraints: task.constraints, dependencies: task.dependencies, expected_outcome: task.expected_outcome, approval: { required: task.approval_required, status: task.approval_required ? "pending" : "not_required" }, status: "queued" });
    return plan;
  }
}
function parsePlan(text: string): any {
  const trimmed = text.trim();
  const candidate = trimmed.startsWith("```") ? trimmed.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "") : trimmed;
  try { return JSON.parse(candidate); } catch { throw new Error("LLM returned invalid JSON for orchestration plan."); }
}