import {getDashboardSummary} from "../lib/dashboard";
const Metric=({label,value,detail}:{label:string;value:number|string;detail?:string})=><div className="card"><div className="sub">{label}</div><div className="value">{value}</div>{detail&&<div className="meta">{detail}</div>}</div>;
export default async function Home(){
 const d=await getDashboardSummary();
 if(!d)return <main style={{maxWidth:520,margin:"100px auto",padding:24}}><h1>CompanyForge</h1><p>No company has been created for this account yet.</p></main>;
 const m=d.metrics;
 return <div className="shell"><aside className="side"><div className="brand">CompanyForge</div><nav className="nav"><div className="active">Command Center</div><a href="/companies/new">Create Company</a><a href="/website">Website Engine</a><a href="/approvals">Approvals</a><a href="/analytics">Analytics</a><div>Agents</div><div>Tasks</div><div>Memory</div><div>Settings</div></nav></aside>
 <main className="main"><header className="top"><div><div className="eyebrow">AI COMPANY OPERATING SYSTEM</div><h1 className="title">{d.companyName}</h1><div className="sub">Visitors, customers, earnings and autonomous operations in one view.</div></div><div className="status">● {d.status}</div></header>
 <section className="metrics"><Metric label="Visitors" value={m.visitors.toLocaleString()} detail={`${m.uniqueVisitors.toLocaleString()} unique`}/><Metric label="Customers" value={m.customers.toLocaleString()} detail={`${(m.conversionRate*100).toFixed(1)}% visitor conversion`}/><Metric label="Earnings" value={`${m.currency} ${m.earnings.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`} detail={`${m.leads.toLocaleString()} leads`}/><Metric label="Running tasks" value={d.runningTasks}/><Metric label="Pending approvals" value={d.pendingApprovals}/><Metric label="Active agents" value={d.activeAgents}/><Metric label="Open incidents" value={d.openIncidents}/><Metric label="Failed tasks" value={d.failedTasks}/></section>
 <section className="panels"><div className="panel"><h2>Company objective</h2><div className="row"><div><b>Goal</b><div className="meta">{d.goal}</div></div></div><div className="row"><div><b>Target customer</b><div className="meta">{d.targetCustomer}</div></div></div></div><div className="panel"><h2>Business performance</h2><div className="row"><div><b>Visitors</b><div className="meta">Tracked from acquisition and company metric events</div></div><span className="pill">{m.visitors}</span></div><div className="row"><div><b>Earnings</b><div className="meta">Only recorded revenue events; no estimates</div></div><span className="pill">{m.currency} {m.earnings.toFixed(2)}</span></div><div className="row"><div><b>Customers</b><div className="meta">Purchases and subscriptions recorded</div></div><span className="pill">{m.customers}</span></div></div>
 <div className="panel"><h2>Recent tasks</h2>{d.recentTasks.length===0?<div className="row"><div><b>No tasks yet</b><div className="meta">Create a company goal to start the AI workforce.</div></div></div>:d.recentTasks.map(t=><div className="row" key={t.id}><div><b>{t.objective}</b><div className="meta">{t.agent}</div></div><span className="pill">{t.status}</span></div>)}</div></section>
 <section className="panel"><h2>Operations</h2><div className="row"><div><b>Open incidents</b><div className="meta">Service health issues awaiting resolution</div></div><span className="pill">{d.openIncidents}</span></div><div className="row"><div><b>Failed tasks</b><div className="meta">Runtime tasks that ended unsuccessfully</div></div><span className="pill">{d.failedTasks}</span></div></section><section className="panel"><h2>Company controls</h2><div className="row"><div><b>Autonomy</b><div className="meta">Current execution policy</div></div><span className="pill">{d.autonomy}</span></div><div className="row"><div><b>Approvals</b><div className="meta">Human control over risky actions</div></div><span className="pill">{d.pendingApprovals} pending</span></div><div className="row"><div><b>Evidence rule</b><div className="meta">Revenue and activity are shown only from recorded events.</div></div><span className="pill">Verified data</span></div></section>
 </main></div>;
}