import type {WebsiteSpec,WebsiteSiteType} from "./types";
const basePages:any={business:[["/","Explain the problem, offer and proof","Get started"],["/about","Build trust and explain the company","Learn more"],["/how-it-works","Explain the product/service journey","Get started"],["/pricing","Make the commercial offer clear","Choose a plan"],["/faq","Resolve purchase objections","Get started"],["/contact","Provide a human contact path","Contact us"]],saas:[["/","Explain product value","Start free"],["/features","Explain capabilities","Start free"],["/pricing","Present plans","Choose a plan"],["/security","Explain trust and security","Talk to sales"],["/docs","Help users succeed","Read docs"],["/contact","Sales/support path","Talk to us"]],commerce:[["/","Merchandise and value proposition","Shop now"],["/shop","Product discovery","View product"],["/product","Product detail","Add to cart"],["/about","Brand story","Explore"],["/faq","Purchase objections","Shop now"],["/contact","Support","Contact us"]]};
export function createWebsiteSpec(input:{companyId:string;name:string;description:string;targetCustomer:string;desiredOutcome:string;siteType:WebsiteSiteType;include3D:boolean}):WebsiteSpec{
 const raw=basePages[input.siteType]||basePages.business; const pages=raw.map((x:string[])=>({path:x[0],purpose:x[1],primaryCta:x[2]}));
 const assets:WebsiteSpec["assets"]=[
  {type:"logo",purpose:"Brand identity",prompt:"Create a distinctive identity for "+input.name+", aimed at "+input.targetCustomer+"."},
  {type:"image",purpose:"Hero visual",prompt:"Create a premium hero visual communicating "+input.description+" for "+input.targetCustomer+"."},
  {type:"illustration",purpose:"Supporting explanation",prompt:"Create supporting visuals explaining the value of "+input.name+" without generic stock imagery."}
 ];
 if(input.include3D) assets.push({type:"3d_scene",purpose:"Interactive explanation",prompt:"Design a purposeful 3D experience for "+input.name+" that clarifies the offer or improves conversion, not decoration."});
 return {companyId:input.companyId,siteType:input.siteType,positioning:input.description+" for "+input.targetCustomer+", optimized around "+input.desiredOutcome, pages,sections:pages.flatMap(p=>[{page:p.path,name:"Hero",purpose:p.purpose},{page:p.path,name:"Proof / trust",purpose:"Reduce uncertainty"},{page:p.path,name:"CTA",purpose:p.primaryCta}]),visualSystem:{tone:"credible, modern, conversion-focused",colors:[],typography:"selected by brand agent",imagery:"original/generated visuals preferred over generic stock"},assets,features:["Responsive layout","SEO foundation","Accessibility","Analytics-ready","Conversion CTAs"],seo:{titleTemplate:input.name+" — {{page}}",description:input.description,keywords:[]},performance:{threeDBudget:input.include3D?"Lazy-load noncritical 3D; core content must work without it.":"No 3D until justified.",imagePolicy:"Use responsive optimized images with meaningful alt text."},acceptance:["Every primary CTA has a defined destination","Mobile and desktop layouts are usable","Core content works without decorative JavaScript","No asset is ready without evidence","No deployment is successful without a real deployment result"]};
}